# Site Info
title: ""
tagline: ""
description: ""
baseurl: ""
url: https:/Seulgi-S.github.io(Repository 주소)
logo: ""

# Site configurations
#gems:
#  - jekyll-paginate
#markdown: kramdown
#kramdown:
#  input: GFM
#excerpt_separator: "<!-- more -->"
sass
  style: compressed
  sass_dir: _scss
#paginate:
#paginate_path: ''
#permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Seul gi Kim(자신의 이름)
  description: Seul gi Kim(자신의 이름)
  contact:
    # linkedin:  https://www.linkedin.com/in/
    github:    https://github.com/Seulgi-S(자신의 깃주소)
    #    facebook:
    # twitter:
    # weibo:
    email:    mailto:sgi7802@kakao.com(자신의 이메일)

google_analytics:
  ua: 'G-SZ1NPRPE9J'

theme: jekyll-theme-cayman
