# Site Info
title: ""
tagline: ""
description: ""
baseurl: ""
url: https://gyu-hyung.github.io/gyu-hyung.git.io/
logo: ""

# Site configurations
#gems:
#  - jekyll-paginate
#markdown: kramdown
#kramdown:
#  input: GFM
#excerpt_separator: "<!-- more -->"
sass
  style: compressed
  sass_dir: _scss
#paginate:
#paginate_path: ''
#permalink: pretty

version: 1.0.0

# About/contact
author:
  name: jo
  description: jo
  contact:
    # linkedin:  https://www.linkedin.com/in/
    github:    https://github.com/gyu-hyung
    #    facebook:
    # twitter:
    # weibo:
    email:   https://gyu-hyung.github.io/gyu-hyung.git.io/

google_analytics:
  ua: 'G-SZ1NPRPE9J'

theme: jekyll-theme-cayman
